blank_issues_enabled: false
contact_links:
  - name: 与 Maa 有关的问题
    url: https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/new/choose
    about: 请在 Maa 仓库里提出
  - name: 与 MaaX 有关的问题
    url: https://github.com/MaaAssistantArknights/MaaX/issues/new/choose
    about: 请在 MaaX 仓库里提出
  - name: 与作业站有关的问题
    url: https://github.com/MaaAssistantArknights/maa-copilot-frontend/issues/new
    about: 请在作业站仓库里提出
